import Cookies from 'js-cookie';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import ProfileCard from '~/components/dashboard/ProfileCard';

type User = {
  name: string;
  email: string;
  password: string;
  createdAt: string;
  updatedAt: string;
  id: string;
};

export default function Dashboard() {
  const [user, setUser] = useState<User | null>(null);
  const [token, setToken] = useState<string | null>(null);

  const router = useRouter();

  useEffect(() => {
    const temp_token = Cookies.get('token');
    const temp_user = Cookies.get('user');

    if (!temp_token || !temp_user) {
      void router.push('/');
      return;
    }

    setToken(temp_token);

    try {
      const parsedUser = JSON.parse(temp_user) as User | null;
      setUser(parsedUser);
    } catch (error) {
      console.error('Error parsing user JSON:', error);
      setUser(null);
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Expenso - Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-[#f1f1f1] flex items-center justify-center py-10'>
        <div className='bg-white min-h-screen max-w-[1024px] w-full shadow-sm rounded-lg'>
        {token && user && (
          <ProfileCard user={user} />
        )}
        </div>
      </main>
    </>
  );
}
